monitoring.exporter.producer.type=log_analytics
monitoring.exporter.producer.log_analytics.data.collection.endpoint=https://dce-dbk-dataplatform-monitoringtool-qa-001-z705.westeurope-1.ingest.monitor.azure.com
monitoring.exporter.producer.log_analytics.data.collection.rule.id=dcr-21142197c844438698896082a7d56608
monitoring.exporter.producer.log_analytics.data.collection.rule.stream=Custom-MonitoringRawData
monitoring.exporter.producer.log_analytics.authentication.type=client_secret
monitoring.exporter.producer.log_analytics.tenant.id=5e781b70-a085-40d6-a5b0-18cc940092c6
monitoring.exporter.producer.log_analytics.client.id=<QA - DBT APP Registration ID>
monitoring.exporter.producer.log_analytics.client.secret.name=<QA - DBT APP Registration Secret Name>

monitoring.exporter.secret.manager.type=databricks
monitoring.exporter.secret.manager.databricks.secret.scope=<Project Secret Scope>