name: cicd-egress

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches:
      - dev_develop
      - dev_master
    types:
      - opened
      - reopened
      - ready_for_review
      - closed
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: "Branch or tag to deploy to PRO"
        required: true
        default: dev_master
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  #request-reviewer-for-master-pr:
    #name: Request reviewer on PR to dev_master
    #if: >
      #github.event_name == 'pull_request' &&
      #github.event.pull_request.base.ref == 'dev_master' &&
      #github.event.action != 'closed' &&
      #github.event.pull_request.draft == false
    #runs-on: ubuntu_latest

    #steps:
      #- name: Request specific reviewer
        #uses: actions/github-script@v7
        #env:
          #REVIEWER_USERNAME: ${{ secrets.PRO_APPROVER_USERNAME }}
        #with:
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          #script: |
            #const reviewer = process.env.REVIEWER_USERNAME;
            
            #try {
              #await github.rest.pulls.requestReviewers({
                #owner: context.repo.owner,
                #repo: context.repo.repo,
                #pull_number: context.payload.pull_request.number,
                #reviewers: [reviewer]
              #});
              #core.info('Reviewer requested: ${reviewer}');
            #} catch (error) {
              #if (error.status === 422) {
                #core.info('Reviewer ${reviewer} already requested, already reviewed, or cannot be requested.');
              #} else {
                #throw error;
              #}
            #}
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev_develop'
    name: Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build package
        run: mvn -B clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-dev-${{ github.sha }}
          path: target/*.jar
          if-no-files-found: error

  deploy-dev:
    name: Deploy to DEV Databricks
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-dev-${{ github.sha }}
          path: target
      #- run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      #- run: databricks repos update /Shared/asp-cldtlk-lkdaex --branch dev_develop
      #- run: |
          #mkdir -p deploy-config
          #cp config/*.conf deploy-config/ 2>/dev/null || true
          #cp config/*.properties deploy-config/ 2>/dev/null || true
          #databricks fs cp deploy-config/ dbfs:/FileStore/configs/dev/ --recursive --overwrite
      #- run: |
          #JAR_FILE=$(ls target/*.jar | head -n 1)
          #JAR_NAME=$(basename "$JAR_FILE")
          #databricks fs cp "$JAR_FILE" \
            #"dbfs:/Volumes/aspd1/default/libs/exporter/app-dev.jar" \
            #--overwrite

  create-pr-to-master: #Creates PR to master if not exists
    name: Create PR to master
    runs-on: ubuntu-24.04
    environment: pre
    needs: deploy-dev
    permissions:
      contents: write
      pull-requests: write
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} #Token responsible for creating PR
    steps: 
      - name: Check if PR exists
        id: pr_check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_TOKEN }} #Token responsible for PR creation
          script: |
            const source = "dev_develop";
            const target = "dev_master";
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${source}`,
              base: target
            });
            return prs.data.length > 0 ? prs.data[0].number : null
 
      - name: Create Pull Request if none exists #Creates PR with review request, if there are no commits (differences) skips this step
        if: steps.pr_check.outputs.result == 'null'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_TOKEN }} #Token responsible for PR creation
          script: |
            const source = "dev_develop";
            const target = "dev_master";

            const compare = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: target,
              head: source
            });
            if (compare.data.total_commits === 0) {
              core.info(`No new commits between ${source} and ${target}. Skipping PR creation.`);
              return;
            }
 
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Automerge ${source} → ${target}`,
              head: source,
              base: target,
              body: `Pull request created automatically by workflow. Requires approval.`
            });
            console.log(`PR created: ${pr.data.html_url}`);
            return pr.data.number

  deploy-pre:
    name: Merge to Master and Deploy to PRE Databricks
    runs-on: ubuntu-latest
    environment: pre
    needs: create-pr-to-master
    if: |
      (
        (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') ||
        (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
      ) &&
      (
        (github.event.pull_request.base.ref == 'dev_master' && github.event.pull_request.head.ref == 'dev_develop')
      )
    permissions:
      contents: write

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PRE_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PRE_TOKEN }}

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: dev_master
      - name: Configure Git #Personal infos necessary to merge and deploy
        run: |
          git config user.name "mariana27oliveira" # USER
          git config user.email "marianarodriguesoliveira2001@gmail.com" #CHANGE USER
 
      - name: Merge source into target #Merge code
        run: |
          git fetch origin dev_develop
          git merge -X theirs origin/dev_develop --allow-unrelated-histories --no-edit
          git push origin dev_master

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-dev-${{ github.sha }}
          path: target
      #- run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      #- run: databricks repos update /Shared/asp-cldtlk-lkdaex --branch dev_master
      #- run: |
          #mkdir -p deploy-config
          #cp config/*.conf deploy-config/ 2>/dev/null || true
          #cp config/*.properties deploy-config/ 2>/dev/null || true
          #databricks fs cp deploy-config/ dbfs:/FileStore/configs/pre/ --recursive --overwrite
      #- run: |
          #JAR_FILE=$(ls target/*.jar | head -n 1)
          #JAR_NAME=$(basename "$JAR_FILE")
          #databricks fs cp "$JAR_FILE" \
            #"dbfs:/Volumes/aspi1/default/libs/exporter/app-pre.jar" \
            #--overwrite

  deploy-pro:
    name: Deploy to PRO Databricks
    runs-on: ubuntu-latest
    needs: deploy-pre
    environment: pro

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PRO_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PRO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-dev-${{ github.sha }}
          path: target
      #- run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      #- run: databricks repos update /Shared/asp-cldtlk-lkdaex --branch dev_master
      #- run: |
          #mkdir -p deploy-config
          #cp config/*.conf deploy-config/ 2>/dev/null || true
          #cp config/*.properties deploy-config/ 2>/dev/null || true
          #databricks fs cp deploy-config/ dbfs:/FileStore/configs/prod/ --recursive --overwrite
      #- run: |
          #JAR_FILE=$(ls target/*.jar | head -n 1)
          #JAR_NAME=$(basename "$JAR_FILE")
          #databricks fs cp "$JAR_FILE" \
            #"dbfs:/Volumes/aspi1/default/libs/exporter/app-pro.jar" \
            #--overwrite
